### ISSUE TITLE
Messy root directory needs a little clean and attention

### ISSUE THREAD

**Issue by githubteacher** [githubschool/recipes#286]
Hey there @matthewmccullough, @allthedoll, @crichID, Looks like this project has been a bit abandoned. Thinking about cleaning up the root directory so that no loose `.md` files are floating about.

**Comment by githubteacher** [comment]
Oh, nearly forgot to include @jordanmccullough.

**Comment by matthewmccullough** [comment]
Go for it!  Who are you beneath that mask, savior of the repo, @githubteacher ?

**Comment by allthedoll** [comment]
It's a mystery!

![mystery](https://pmcdeadline2.files.wordpress.com/2014/06/scoobydo.jpg?w=446&h=299&crop=1)

**Comment by allthedoll** [comment]
I think it's Old Man Smithers. Or @patrickmckenna.

**Comment by githubteacher** [comment]
Closing this down as I just noticed @jordanmccullough opened the PR. Let's explore further over there and discuss any remaining cleanup.

**Comment by patrickmckenna** [comment]
> I think it's Old Man Smithers. Or @patrickmckenna.

:smirk_cat:
